name: flip8
description: A flutter implementation of a CHIP-8 virtual machine.

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/blank.png
